name: 'Start local Dash network'
description: 'Invokes dashmate to set up a local network for CI'
inputs:
  dashmate-branch:
    description: 'dashmate branch to use'
  dapi-branch:
    description: 'dapi branch to be injected into dashmate'
  drive-branch:
    description: 'drive branch to be injected into dashmate'
  sdk-branch:
    description: 'Dash SDK (DashJS) branch to be injected into dashmate'
  actions-cache-url:
    description: ''
  actions-cache-token:
    description: ''
outputs:
  test-output:
    description: 'Should pass output here'


runs:
  using: composite
  steps:
    - name: Set up tools
      shell: bash
      working-directory: ${{ github.action_path }}
      run: npm ci && npm link

    - name: Start local network
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        ACTIONS_CACHE_URL: ${{ inputs.actions-cache-url }}
        ACTIONS_RUNTIME_TOKEN: ${{ inputs.actions-cache-token }}
      run: |
        source bin/start-local-node.sh \
          --override-major-version=0 \
          --dashmate-branch=${{ inputs.dashmate-branch }} \
          --dapi-branch=${{ inputs.dapi-branch }} \
          --drive-branch=${{ inputs.drive-branch }} \
          --sdk-branch=${{ inputs.sdk-branch }}

    - name: Test if output is set in composite
      shell: bash
      run: |
        echo 'In composite output test step'
        echo $test-output
