name: 'Start local Dash network'
description: 'Invokes mn-bootstrap to set up a local network for CI'
inputs:
  dashmate-branch:
    description: 'dashmate branch to use'
  dapi-branch:
    description: 'dapi branch to be injected into mn-bootstrap'
  drive-branch:
    description: 'drive branch to be injected into mn-bootstrap'
  install-sdk-version:
    description: 'Dash SDK (DashJS) branch to be injected into mn-bootstrap'

runs:
  using: composite
  steps:
    - name: Set up tools
      shell: bash
      working-directory: ${{ github.action_path }}
      run: npm ci && npm link

    - name: Echo GH Workspace
      shell: bash
      run: |
        echo $GITHUB_WORKSPACE
        cat $GITHUB_WORKSPACE/package.json

    - name: Start local network
      shell: bash

      working-directory: ${{ github.action_path }}
      run: |
        source bin/start-local-node.sh $GITHUB_WORKSPACE/package.json \
          --override-major-version=0 \
          --dashmate-branch=${{ inputs.dashmate-branch }} \
          --dapi-branch=${{ inputs.dapi-branch }} \
          --drive-branch=${{ inputs.drive-branch }} \
          --sdk-branch=${{ inputs.install-sdk-version }}
