  name: 'Start local Dash network'
description: 'Invokes mn-bootstrap to set up a local network for CI'
inputs:
  dashmate-branch:
    description: 'dashmate branch to use'
  dapi-branch:
    description: 'dapi branch to be injected into mn-bootstrap'
  drive-branch:
    description: 'drive branch to be injected into mn-bootstrap'
  install-sdk-version:
    description: 'Dash SDK (DashJS) branch to be injected into mn-bootstrap'

runs:
  using: node12
  main: test.js
